"""Small on-demand drawing takeoff panel; existing PDF renderer stays in charge."""
STYLE='''<style>
#bt-panel{position:fixed;right:10px;top:58px;z-index:55;width:min(310px,calc(100vw - 20px));max-height:calc(100dvh - 112px);overflow:auto;box-sizing:border-box;background:#fff;border:1px solid #becddb;border-radius:10px;box-shadow:0 8px 24px #10273c30;padding:12px;color:#17354a;font:13px/1.4 Arial,sans-serif}
#bt-panel.bt-drawing{padding:8px;width:min(274px,calc(100vw - 20px))}#bt-panel.bt-drawing #bt-status{font-size:12px;margin:6px 0}#bt-panel.bt-drawing .bt-row{margin:6px 0}#bt-panel.bt-drawing>p,#bt-panel.bt-drawing>label,#bt-panel.bt-drawing>#bt-group,#bt-panel.bt-drawing>#bt-new,#bt-panel.bt-drawing #bt-current>label,#bt-panel.bt-drawing #bt-location,#bt-panel.bt-drawing #bt-total,#bt-panel.bt-drawing #bt-current>details,#bt-panel.bt-drawing #bt-current>.bt-help,#bt-panel.bt-drawing #bt-list,#bt-panel.bt-drawing #bt-links{display:none}#bt-panel.bt-drawing #bt-draw{display:none}@media(max-width:650px){#bt-panel.bt-drawing{top:auto;bottom:54px;right:10px;max-height:210px}}
#bt-panel[hidden]{display:none!important}#bt-panel h2{font:700 16px Arial;margin:0}#bt-panel p{margin:8px 0}#bt-panel label{display:block;font-size:12px;margin-top:8px}#bt-panel input,#bt-panel select{width:100%;box-sizing:border-box;border:1px solid #bfcedb;border-radius:5px;padding:7px;font:13px Arial;min-height:34px;background:#fff;color:#17354a}#bt-panel button,#bt-panel a.bt-button{min-height:32px;padding:6px 9px;border:1px solid #c4d2dd;border-radius:5px;background:#f1f5f8;color:#17354a;font:600 12px Arial;margin:0;cursor:pointer;text-decoration:none}#bt-panel button:disabled{opacity:.55;cursor:wait}#bt-panel .bt-primary{background:#173f60;color:white;border-color:#173f60}#bt-panel .bt-row{display:flex;gap:5px;align-items:center;flex-wrap:wrap;margin:8px 0}#bt-panel .bt-head{display:flex;align-items:center;justify-content:space-between}#bt-panel .bt-help{color:#526b7f;font-size:12px}#bt-status{padding:8px;background:#edf3f7;border-radius:5px;overflow-wrap:anywhere}#bt-list{max-height:220px;overflow:auto}#bt-list>div{border-top:1px solid #dce4eb;padding:8px 0}#bt-list button{font-size:11px;padding:4px 6px;min-height:28px}#bt-total{padding:9px;background:#eef5f8;border-radius:6px}#bt-overlay{position:absolute;inset:0;width:100%;height:100%;z-index:19;pointer-events:none;overflow:visible}#bt-overlay.bt-active{pointer-events:auto;touch-action:none;cursor:crosshair}#bt-overlay *{pointer-events:none}#bt-panel:focus-visible,#bt-panel button:focus-visible,#bt-panel a:focus-visible{outline:2px solid #ba831c;outline-offset:2px}#bt-panel details{margin:8px 0}#bt-panel summary{cursor:pointer;font-weight:600}
@media(pointer:coarse){#bt-panel button,#bt-panel a.bt-button{min-height:40px}#bt-list button{min-height:40px}}
</style>'''
PANEL='''<aside id="bt-panel" hidden aria-label="Drawing takeoff">
<div class="bt-head"><h2>Takeoff</h2><button id="bt-expand" type="button" aria-label="Expand or minimize takeoff">Minimize</button><button id="bt-close" type="button" aria-label="Close takeoff">Close</button></div>
<p class="bt-help">Choose an item. Trace, outline or count. Save each room separately.</p>
<label for="bt-group">Trade / item</label><select id="bt-group"><option value="">Create your first item</option></select>
<details id="bt-new"><summary>New takeoff item</summary>
<label for="bt-rate">Use a saved company rate</label><select id="bt-rate"><option value="">Choose a rate or enter an item</option></select>
<label for="bt-trade">Trade</label><input id="bt-trade" maxlength="80" list="bt-trades" placeholder="Tile, Framing, Plumbing...">
<datalist id="bt-trades"><option>Tile</option><option>Framing</option><option>Plumbing</option><option>Electrical</option><option>Concrete</option><option>Drywall</option><option>Flooring</option><option>Painting</option></datalist>
<label for="bt-name">Material / item</label><input id="bt-name" maxlength="120" placeholder="12 x 24 floor tile, hot water pipe...">
<div class="bt-row"><label>Measure<select id="bt-kind"><option value="area">Area</option><option value="length">Length</option><option value="count">Count</option></select></label><label>Unit<select id="bt-unit"><option>SF</option><option>M2</option></select></label></div>
<div class="bt-row"><label>Material / unit<input id="bt-material" type="number" min="0" max="1000000" step="0.01" value="0"></label><label>Labor / unit<input id="bt-labor" type="number" min="0" max="1000000" step="0.01" value="0"></label></div>
<label for="bt-waste">Waste %</label><input id="bt-waste" type="number" min="0" max="100" step="0.1" value="0">
<div class="bt-row"><button id="bt-create" type="button">Create item</button><a id="bt-rates-link" href="/workspace/takeoff-rates">Company rate book</a></div></details>
<div id="bt-current" hidden><label for="bt-location">Room / location</label><input id="bt-location" maxlength="120" placeholder="Lobby, restroom 101, north wall...">
<div class="bt-row"><button id="bt-draw" type="button" class="bt-primary">Draw area</button><button id="bt-pan" type="button">Pan</button><button id="bt-undo" type="button">Undo point</button></div>
<div class="bt-row"><button id="bt-save" type="button" class="bt-primary">Finish & save</button><button id="bt-cancel" type="button">Cancel</button></div>
<p id="bt-status" role="status" aria-live="polite">Choose Draw to start.</p><div id="bt-total"></div>
<details><summary>Waste & rates</summary><label>Waste %<input id="bt-edit-waste" type="number" min="0" max="100" step="0.1"></label><label>Material / unit<input id="bt-edit-material" type="number" min="0" max="1000000" step="0.01"></label><label>Labor / unit<input id="bt-edit-labor" type="number" min="0" max="1000000" step="0.01"></label><button id="bt-settings" type="button">Save defaults</button><p class="bt-help">Material uses quantity with waste; labor uses net area or length. Estimate transfer reviews quantity separately.</p></details>
<p class="bt-help">Saved on this sheet</p><div id="bt-list"></div><div class="bt-row" id="bt-links"><a id="bt-review" class="bt-button">Review & estimate</a><a id="bt-all">All trade items</a></div></div>
<p class="bt-help">Check scale against a known dimension. Drawing measurements require estimator review.</p></aside>'''
SCRIPT=r'''
(()=>{'use strict';
const cfg=window.BC_TAKEOFF_CONFIG,$=id=>document.getElementById(id),panel=$('bt-panel'),stage=$('bcStage'),bar=document.querySelector('#dfp-menu nav.df-actions');
if(!panel||!stage||!bar)return;
const base='/workspace/drawing-takeoff',NS='http://www.w3.org/2000/svg';
const menu=document.createElement('button');menu.type='button';menu.id='bt-open';menu.textContent='Takeoff';menu.setAttribute('aria-controls','bt-panel');menu.setAttribute('aria-expanded','false');bar.insertBefore(menu,bar.firstChild?.nextSibling||null);
const svg=document.createElementNS(NS,'svg');svg.id='bt-overlay';svg.setAttribute('viewBox','0 0 1000 1000');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-label','Drawing takeoff outlines');stage.append(svg);
let data=null,selected='',draft=[],cutout=null,pending=null,busy=false,active=false,rates=[];
const money=n=>Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const uid=()=>crypto.randomUUID().replaceAll('-',''),fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:3}),entry=()=>data?.groups.find(x=>String(x.group.id)===selected);
function status(s){$('bt-status').textContent=s;}
async function req(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,redirect:'error'});const type=r.headers.get('content-type')||'';const result=type.includes('application/json')?await r.json():{error:new DOMParser().parseFromString(await r.text(),'text/html').querySelector('p')?.textContent};if(!r.ok)throw Error(result.error||'Reopen the drawing to check your access.');return result;}
function lock(on){busy=on;panel.querySelectorAll('button,select,input').forEach(e=>e.disabled=on);}
async function run(fn){if(busy)return;lock(true);try{await fn();}catch(e){status(e.message||'Connection interrupted. Your outline is still here; retry Finish & save.');$('bt-current').hidden=false;}finally{lock(false);}}
async function load(){data=await req(base+'/sheets/'+cfg.sheet_id);const previous=selected;$('bt-group').replaceChildren();for(const s of data.groups){const o=new Option(s.group.trade+' · '+s.group.name,String(s.group.id));$('bt-group').add(o);}selected=data.groups.some(s=>String(s.group.id)===previous)?previous:String(data.groups[0]?.group.id||'');$('bt-group').value=selected;$('bt-new').open=!selected;render();}
function mode(on){active=on;if(on){panel.classList.add('bt-drawing');$('bt-expand').textContent='Expand';}svg.classList.toggle('bt-active',on);$('bcPan')?.click();if(on){$('dfp-close-tools')?.click();$('dw-close')?.click();document.body.classList.add('df-sheets-hidden');} }
function clear(){draft=[];cutout=null;pending=null;mode(false);panel.classList.remove('bt-drawing');$('bt-expand').textContent='Minimize';paint();}
function shapeNode(kind,p,color,dashed=false){const node=document.createElementNS(NS,kind==='area'?'polygon':'polyline');node.setAttribute('points',p.map(q=>q.map(v=>v*1000).join(',')).join(' '));node.setAttribute('fill',kind==='area'?color+'22':'none');node.setAttribute('stroke',color);node.setAttribute('stroke-width','2');node.setAttribute('vector-effect','non-scaling-stroke');if(dashed)node.setAttribute('stroke-dasharray','6 4');svg.append(node);}
function countNode(p,color){const rect=svg.getBoundingClientRect(),rx=6000/Math.max(rect.width,1),ry=6000/Math.max(rect.height,1);for(const q of p){const node=document.createElementNS(NS,'ellipse');node.setAttribute('cx',q[0]*1000);node.setAttribute('cy',q[1]*1000);node.setAttribute('rx',rx);node.setAttribute('ry',ry);node.setAttribute('fill',color+'44');node.setAttribute('stroke',color);node.setAttribute('stroke-width','2');node.setAttribute('vector-effect','non-scaling-stroke');svg.append(node);}}
function paint(){svg.replaceChildren();const s=entry();if(panel.hidden||!s)return;for(const m of s.marks.filter(x=>x.sheet_id===cfg.sheet_id)){const sh=m.measurement.shape,color=m.stale?'#ac6517':'#157585';if(s.group.kind==='count')countNode(sh.points,color);else{shapeNode(s.group.kind,sh.points,color);for(const h of sh.holes)shapeNode('area',h,'#b84b52',true);}}if(draft.length){if(s.group.kind==='count'&&!cutout)countNode(draft,'#be6710');else shapeNode(cutout?'area':s.group.kind,draft,'#be6710',true);}}
function btn(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b;}
function render(){const s=entry();$('bt-current').hidden=!s;if(!s){paint();return;}const g=s.group,t=s.totals;$('bt-draw').textContent=g.kind==='count'?'Count items':'Draw '+g.kind;$('bt-edit-waste').value=g.waste;$('bt-edit-material').value=g.material_rate||0;$('bt-edit-labor').value=g.labor_rate||0;
$('bt-total').textContent='Net '+fmt(t.net)+' '+g.unit+' · Waste '+fmt(t.waste_pct)+'% · Quantity '+fmt(t.quantity)+' '+g.unit+' · Price '+money(t.quantity*(g.material_rate||0)+t.net*(g.labor_rate||0))+' (company currency)';
$('bt-review').href=base+'/groups/'+g.id;$('bt-all').href=base+'/projects/'+cfg.project_id;$('bt-list').replaceChildren();
for(const m of s.marks.filter(x=>x.sheet_id===cfg.sheet_id)){const div=document.createElement('div'),title=document.createElement('p'),actions=document.createElement('div');title.textContent=m.label+' · '+fmt(m.measurement.net)+' '+g.unit+(m.stale?' · Recheck scale':'');actions.className='bt-row';div.append(title,actions);
if(g.kind==='area'&&!m.stale)actions.append(btn('Cut out',()=>{if(draft.length&&!confirm('Discard the unfinished outline?'))return;clear();cutout=m;mode(true);status('Click corners inside '+m.label+'. Finish & save removes that area.');}));
if(m.stale&&data.scale.current)actions.append(btn('Recheck scale',()=>run(async()=>{if(!confirm('Recalculate '+m.label+' using the current sheet and detail scales? Saved estimate quantities will not change. Any unfinished outline will be discarded.'))return;clear();await saveShape(m.measurement.shape,m.label,m.id);clear();await load();status('Recalculated. Review the new quantity before estimate transfer.');})));
actions.append(btn('Remove',()=>run(async()=>{if(!confirm('Remove this saved measurement and its cutouts?'))return;await req(base+'/groups/'+g.id+'/marks/'+m.id+'/remove',{version:g.version});await load();status('Measurement removed. Estimate quantity is unchanged.');})));$('bt-list').append(div);}
paint();}
function stamp(){const s=entry(),v=data.scale;return {sheet_id:v.sheet_id,source_key:v.source_key,...(s.group.kind==='count'?{}:{version:v.version,areas_revision:v.areas_revision||0})};}
async function saveShape(shape,label,mid){const g=entry().group;if(!pending)pending={group_id:g.id,version:g.version,stamp:stamp(),shape,label,request_key:uid(),...(mid?{mark_id:mid}:{})};return req(base+'/sheets/'+cfg.sheet_id+'/marks',pending);}
menu.onclick=()=>run(async()=>{panel.hidden=false;menu.setAttribute('aria-expanded','true');$('dfp-menu').open=false;$('dfp-close-tools')?.click();$('dw-close')?.click();await load();rates=await req('/workspace/takeoff-rates/data');$('bt-rate').replaceChildren(new Option('Choose a rate or enter an item',''));for(const r of rates.rates)$('bt-rate').add(new Option(r.trade+' · '+r.name+' / '+r.unit,String(r.id)));$('bt-group').focus();});
$('bt-expand').onclick=()=>{$('bt-expand').textContent=panel.classList.toggle('bt-drawing')?'Expand':'Minimize';};
$('bt-close').onclick=()=>{if(draft.length&&!confirm('Discard the unfinished outline?'))return;clear();panel.hidden=true;menu.setAttribute('aria-expanded','false');paint();menu.focus();};
$('bt-group').onchange=()=>{if(draft.length&&!confirm('Discard the unfinished outline?')){$('bt-group').value=selected;return;}clear();selected=$('bt-group').value;render();status('Choose Draw to start.');};
$('bt-kind').onchange=()=>{const k=$('bt-kind').value;$('bt-unit').replaceChildren(...({area:['SF','M2'],length:['LF','M'],count:['EA']}[k]).map(u=>new Option(u,u)));if(k==='count')$('bt-waste').value=0;};
$('bt-rate').onchange=()=>{const r=rates.rates.find(x=>String(x.id)===$('bt-rate').value);if(!r)return;$('bt-name').value=r.name;$('bt-trade').value=r.trade;$('bt-kind').value=r.kind;$('bt-kind').onchange();$('bt-unit').value=r.unit;$('bt-material').value=r.material_rate;$('bt-labor').value=r.labor_rate;$('bt-waste').value=r.waste;};
let createPending=null;
$('bt-create').onclick=()=>run(async()=>{const values={name:$('bt-name').value,trade:$('bt-trade').value,kind:$('bt-kind').value,unit:$('bt-unit').value,waste:Number($('bt-waste').value),material_rate:Number($('bt-material').value),labor_rate:Number($('bt-labor').value)};const signature=JSON.stringify(values);if(!createPending||createPending.signature!==signature)createPending={signature,body:{...values,request_key:uid()}};const r=await req(base+'/projects/'+cfg.project_id+'/groups',createPending.body);createPending=null;selected=String(r.group_id);await load();$('bt-new').open=false;$('bt-location').focus();status('Item saved. Enter a room or location, then start measuring.');});
$('bt-draw').onclick=()=>run(async()=>{if(draft.length&&!confirm('Discard the unfinished outline?'))return;clear();await load();if(!data.scale.current)throw Error('Open the current sheet revision to measure.');if(!$('bt-location').value.trim()){$('bt-location').focus();throw Error('Enter a room or location first.');}mode(true);status(entry().group.kind==='count'?'Click each item, then Finish & save.':'Click corners, then Finish & save. Use Pan to move.');});
$('bt-pan').onclick=()=>{mode(!active);status(active?'Continue selecting points.':'Pan enabled. Click Pan again to continue the outline.');};
$('bt-undo').onclick=()=>{draft.pop();pending=null;paint();status(draft.length+' points.');};
$('bt-cancel').onclick=()=>{clear();status('Unfinished outline discarded. Saved quantities are unchanged.');};
$('bt-save').onclick=()=>run(async()=>{const s=entry(),min=cutout||s.group.kind==='area'?3:s.group.kind==='length'?2:1;if(draft.length<min)throw Error('Choose at least '+min+' points.');const shape=cutout?{...cutout.measurement.shape,holes:[...cutout.measurement.shape.holes,draft]}:{points:draft,holes:[]};await saveShape(shape,cutout?cutout.label:$('bt-location').value,cutout?.id);clear();await load();status('Saved. Quantity calculated from the source drawing scale.');});
$('bt-settings').onclick=()=>run(async()=>{const g=entry().group;await req(base+'/groups/'+g.id+'/settings',{version:g.version,waste:Number($('bt-edit-waste').value),material_rate:Number($('bt-edit-material').value),labor_rate:Number($('bt-edit-labor').value)});await load();status('Defaults saved. Existing estimate prices are unchanged.');});
let down=null;
svg.addEventListener('pointerdown',e=>{if(!active||busy)return;e.preventDefault();e.stopPropagation();svg.setPointerCapture(e.pointerId);down=[e.clientX,e.clientY];});
svg.addEventListener('pointerup',e=>{if(!active||busy)return;e.preventDefault();e.stopPropagation();if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>12){down=null;return;}down=null;const r=stage.getBoundingClientRect(),p=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];if(p.some(v=>v<0||v>1))return;if(draft.length>=256){status('Finish this outline before adding more than 256 points.');return;}if(draft.length&&Math.hypot(p[0]-draft.at(-1)[0],p[1]-draft.at(-1)[1])<1e-7)return;draft.push(p);pending=null;paint();status(draft.length+' points selected. Finish & save when ready.');});
svg.addEventListener('pointercancel',()=>down=null);window.addEventListener('bc-drawing-rendered',paint);new ResizeObserver(paint).observe(stage);
window.addEventListener('bc-scale-mode',()=>{mode(false);status('Scale settings opened. Reload Takeoff before continuing.');});
$('df-markup')?.addEventListener('click',()=>{mode(false);panel.hidden=true;paint();});
document.addEventListener('keydown',e=>{if(panel.hidden||document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){mode(false);status('Pan enabled. Your unfinished outline is retained.');}if(e.key==='Enter'&&active){e.preventDefault();$('bt-save').click();}});
window.addEventListener('beforeunload',e=>{if(draft.length){e.preventDefault();e.returnValue='';}});
const requested=new URLSearchParams(location.search).get('takeoff');if(requested){selected=requested;menu.click();}
})();'''
